#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#init -1
import random
import sys

maxLine = 0
file_path = str(sys.argv[1])
file_count = open(file_path)
while True:
    buffer = file_count.read(1024*10)
    if not buffer:
        break
    maxLine += buffer.count('\n')
file_count.close()
file = open(file_path,"r")
random_int = random.randint(0,maxLine-1)
print(file.readlines()[random_int])

